### ISSUE TITLE
Gzip ContentEncoding not working as intended

### ISSUE THREAD

**Issue by mplachter** [DataDog/datadog-api-client-go#1094]
**Describe the bug**
Gzip Content Encoding on v1 Submit log does not seem to be working

**To Reproduce**

1. Use the example Go code with the `gzip` ContentEncoding. Only difference is apply some HTTPLogItems
```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	datadog "github.com/DataDog/datadog-api-client-go/api/v1/datadog"
)

var service = "test_service"
var hostname = "test_host"
var source = "test"
var message = "{\"test_key\": \"test_message\"}"

func main() {
	ctx := datadog.NewDefaultContext(context.Background())

	body := []datadog.HTTPLogItem{{
		Ddsource: &source,
		Hostname: &hostname,
		Service:  &service,
		Message:  &message,
	}} // []HTTPLogItem | Log to send (JSON format).
	contentEncoding := datadog.ContentEncoding("gzip") // ContentEncoding | HTTP header used to compress the media-type. (optional)
	ddtags := "env:prod,user:my-user"                  // string | Log tags can be passed as query parameters with `text/plain` content type. (optional)
	optionalParams := datadog.SubmitLogOptionalParameters{
		ContentEncoding: &contentEncoding,
		Ddtags:          &ddtags,
	}

	configuration := datadog.NewConfiguration()

	apiClient := datadog.NewAPIClient(configuration)
	resp, r, err := apiClient.LogsApi.SubmitLog(ctx, body, optionalParams)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `LogsApi.SubmitLog`: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	// response from `SubmitLog`: interface{}
	responseContent, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Fprintf(os.Stdout, "Response from LogsApi.SubmitLog:\n%s\n", responseContent)
}

```
2. Run the code
3. Check the output
4. Get Error
```bash
Error when calling `LogsApi.SubmitLog`: Required field code missing
Full HTTP response: &{400 Bad Request 400 HTTP/2.0 2 0 map[Content-Length:[2] Content-Type:[application/json] Date:[Thu, 02 Sep 2021 21:10:57 GMT]] {{}} 2 [] false false map[] 0xc000190200 0xc00032f8c0}
Response from LogsApi.SubmitLog:
null
```

**Expected behavior**
I believe the expected behavior is the json body payload would have been gzip and compressed and sent to DD APIs

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - `go version go1.16.6 darwin/amd64`
  - `github.com/DataDog/datadog-api-client-go v1.3.0`

**Additional context**
The code works perfectly if you remove the `gzip` encoding optional parameter.
I believe this issue is caused due to the header being added for gzip encoding but the body never getting encoded with gzip compression.

**Comment by therve** [comment]
Hi,

The content-encoding parameter implies that you're doing the gzip compression yourself in the payload. That said, I think our generated client only supports JSON payload, so I don't know if you can use it to do what you want. I'll reach out to the logs team, thanks.

**Comment by mplachter** [comment]
@therve The big thing is the `SubmitLog` method only takes in an actual list of `HTTPLogItem`. If it took in a `body` field then I would be able to compress it myself.
https://github.com/DataDog/datadog-api-client-go/blob/master/api/v1/datadog/api_logs.go#L238-L256

**Comment by therve** [comment]
Should be fixed by #1119

**Comment by mplachter** [comment]
@therve This is still not working please try my attached example (pulled down the module off of master)

**Comment by mplachter** [comment]
Opened a new issue as I cannot reopen this issue.

https://github.com/DataDog/datadog-api-client-go/issues/1135
